# Generated by Django 4.0 on 2022-12-13 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_visitor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name_plural': '게시판'},
        ),
        migrations.AlterModelOptions(
            name='calender',
            options={'verbose_name_plural': '일정'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': '댓글'},
        ),
        migrations.AlterModelOptions(
            name='communitypost',
            options={'verbose_name_plural': '게시판 글'},
        ),
        migrations.AlterModelOptions(
            name='convenient',
            options={'verbose_name_plural': '편의시설'},
        ),
        migrations.AlterModelOptions(
            name='fee',
            options={'verbose_name_plural': '요금'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '사용자별 알림'},
        ),
        migrations.AlterModelOptions(
            name='securitytodo',
            options={'verbose_name_plural': '경비 업무'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '사용자'},
        ),
        migrations.AlterModelOptions(
            name='visitor',
            options={'verbose_name_plural': '방문차량'},
        ),
        migrations.AddField(
            model_name='convenient',
            name='image_path',
            field=models.CharField(default='traning.jpg', max_length=100),
            preserve_default=False,
        ),
    ]
